[2023-04-23T19:50:25.907-0300] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: trabajo_practico.TopCTR manual__2023-04-23T22:49:19.781564+00:00 [queued]>
[2023-04-23T19:50:25.910-0300] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: trabajo_practico.TopCTR manual__2023-04-23T22:49:19.781564+00:00 [queued]>
[2023-04-23T19:50:25.910-0300] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-23T19:50:25.910-0300] {taskinstance.py:1289} INFO - Starting attempt 2 of 2
[2023-04-23T19:50:25.910-0300] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-23T19:50:25.924-0300] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): TopCTR> on 2023-04-23 22:49:19.781564+00:00
[2023-04-23T19:50:25.927-0300] {standard_task_runner.py:55} INFO - Started process 40487 to run task
[2023-04-23T19:50:25.928-0300] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'trabajo_practico', 'TopCTR', 'manual__2023-04-23T22:49:19.781564+00:00', '--job-id', '85', '--raw', '--subdir', 'DAGS_FOLDER/dag_tp.py', '--cfg-path', '/tmp/tmpywiy7c03']
[2023-04-23T19:50:25.929-0300] {standard_task_runner.py:83} INFO - Job 85: Subtask TopCTR
[2023-04-23T19:50:25.963-0300] {task_command.py:389} INFO - Running <TaskInstance: trabajo_practico.TopCTR manual__2023-04-23T22:49:19.781564+00:00 [running]> on host pepino-ThinkPad-E15-Gen-2
[2023-04-23T19:50:26.045-0300] {taskinstance.py:1516} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=trabajo_practico
AIRFLOW_CTX_TASK_ID=TopCTR
AIRFLOW_CTX_EXECUTION_DATE=2023-04-23T22:49:19.781564+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-23T22:49:19.781564+00:00
[2023-04-23T19:50:26.047-0300] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag_tp.py", line 47, in TopCTR
    datos_filtrados = kwargs['ti'].xcom_pull(task_ids = 'filtrado_task', key = 'datos_top_ctr')[0]
TypeError: 'NoneType' object is not subscriptable
[2023-04-23T19:50:26.049-0300] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=trabajo_practico, task_id=TopCTR, execution_date=20230423T224919, start_date=20230423T225025, end_date=20230423T225026
[2023-04-23T19:50:26.062-0300] {standard_task_runner.py:100} ERROR - Failed to execute job 85 for task TopCTR ('NoneType' object is not subscriptable; 40487)
[2023-04-23T19:50:26.100-0300] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-23T19:50:26.118-0300] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
