[2023-04-17T09:00:24.639-0300] {processor.py:153} INFO - Started process (PID=81614) to work on /home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-17T09:00:24.640-0300] {processor.py:743} INFO - Processing file /home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-17T09:00:24.641-0300] {logging_mixin.py:137} INFO - [2023-04-17T09:00:24.641-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-17T09:00:24.655-0300] {logging_mixin.py:137} INFO - [2023-04-17T09:00:24.654-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-17T09:00:24.655-0300] {logging_mixin.py:137} INFO - [2023-04-17T09:00:24.655-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-17T09:00:24.655-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-17T09:00:24.659-0300] {processor.py:175} INFO - Processing /home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2023-04-17T09:01:10.014-0300] {processor.py:153} INFO - Started process (PID=81728) to work on /home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-17T09:01:10.022-0300] {processor.py:743} INFO - Processing file /home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-17T09:01:10.023-0300] {logging_mixin.py:137} INFO - [2023-04-17T09:01:10.023-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-17T09:01:10.042-0300] {logging_mixin.py:137} INFO - [2023-04-17T09:01:10.042-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-17T09:01:10.042-0300] {logging_mixin.py:137} INFO - [2023-04-17T09:01:10.042-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-17T09:01:10.042-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-17T09:01:10.046-0300] {processor.py:175} INFO - Processing /home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2023-04-17T09:01:55.242-0300] {processor.py:153} INFO - Started process (PID=81826) to work on /home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-17T09:01:55.251-0300] {processor.py:743} INFO - Processing file /home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-17T09:01:55.252-0300] {logging_mixin.py:137} INFO - [2023-04-17T09:01:55.252-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-17T09:01:55.269-0300] {logging_mixin.py:137} INFO - [2023-04-17T09:01:55.269-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-17T09:01:55.269-0300] {logging_mixin.py:137} INFO - [2023-04-17T09:01:55.269-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-17T09:01:55.270-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-17T09:01:55.275-0300] {processor.py:175} INFO - Processing /home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2023-04-17T09:02:39.159-0300] {processor.py:153} INFO - Started process (PID=81909) to work on /home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-17T09:02:39.168-0300] {processor.py:743} INFO - Processing file /home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-17T09:02:39.169-0300] {logging_mixin.py:137} INFO - [2023-04-17T09:02:39.169-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-17T09:02:39.186-0300] {logging_mixin.py:137} INFO - [2023-04-17T09:02:39.186-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-17T09:02:39.186-0300] {logging_mixin.py:137} INFO - [2023-04-17T09:02:39.186-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-17T09:02:39.186-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-17T09:02:39.190-0300] {processor.py:175} INFO - Processing /home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2023-04-17T09:03:23.159-0300] {processor.py:153} INFO - Started process (PID=81997) to work on /home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-17T09:03:23.161-0300] {processor.py:743} INFO - Processing file /home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-17T09:03:23.162-0300] {logging_mixin.py:137} INFO - [2023-04-17T09:03:23.161-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-17T09:03:23.175-0300] {logging_mixin.py:137} INFO - [2023-04-17T09:03:23.174-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-17T09:03:23.175-0300] {logging_mixin.py:137} INFO - [2023-04-17T09:03:23.175-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-17T09:03:23.175-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-17T09:03:23.179-0300] {processor.py:175} INFO - Processing /home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2023-04-17T09:04:08.912-0300] {processor.py:153} INFO - Started process (PID=82136) to work on /home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-17T09:04:08.913-0300] {processor.py:743} INFO - Processing file /home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-17T09:04:08.914-0300] {logging_mixin.py:137} INFO - [2023-04-17T09:04:08.914-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-17T09:04:08.922-0300] {logging_mixin.py:137} INFO - [2023-04-17T09:04:08.922-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-17T09:04:08.922-0300] {logging_mixin.py:137} INFO - [2023-04-17T09:04:08.922-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-17T09:04:08.923-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-17T09:04:08.927-0300] {processor.py:175} INFO - Processing /home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2023-04-17T09:04:50.450-0300] {processor.py:153} INFO - Started process (PID=82257) to work on /home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-17T09:04:50.459-0300] {processor.py:743} INFO - Processing file /home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-17T09:04:50.461-0300] {logging_mixin.py:137} INFO - [2023-04-17T09:04:50.460-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-17T09:04:50.476-0300] {logging_mixin.py:137} INFO - [2023-04-17T09:04:50.476-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-17T09:04:50.476-0300] {logging_mixin.py:137} INFO - [2023-04-17T09:04:50.476-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-17T09:04:50.476-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-17T09:04:50.481-0300] {processor.py:175} INFO - Processing /home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2023-04-17T09:05:42.917-0300] {processor.py:153} INFO - Started process (PID=82374) to work on /home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-17T09:05:42.919-0300] {processor.py:743} INFO - Processing file /home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-17T09:05:42.920-0300] {logging_mixin.py:137} INFO - [2023-04-17T09:05:42.920-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-17T09:05:42.932-0300] {logging_mixin.py:137} INFO - [2023-04-17T09:05:42.932-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-17T09:05:42.932-0300] {logging_mixin.py:137} INFO - [2023-04-17T09:05:42.932-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-17T09:05:42.932-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-17T09:05:42.937-0300] {processor.py:175} INFO - Processing /home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2023-04-17T09:06:44.352-0300] {processor.py:153} INFO - Started process (PID=82533) to work on /home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-17T09:06:44.353-0300] {processor.py:743} INFO - Processing file /home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-17T09:06:44.353-0300] {logging_mixin.py:137} INFO - [2023-04-17T09:06:44.353-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-17T09:06:44.367-0300] {logging_mixin.py:137} INFO - [2023-04-17T09:06:44.366-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-17T09:06:44.367-0300] {logging_mixin.py:137} INFO - [2023-04-17T09:06:44.367-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-17T09:06:44.367-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-17T09:06:44.373-0300] {processor.py:175} INFO - Processing /home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2023-04-17T09:07:38.958-0300] {processor.py:153} INFO - Started process (PID=82649) to work on /home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-17T09:07:38.959-0300] {processor.py:743} INFO - Processing file /home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-17T09:07:38.959-0300] {logging_mixin.py:137} INFO - [2023-04-17T09:07:38.959-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-17T09:07:38.969-0300] {logging_mixin.py:137} INFO - [2023-04-17T09:07:38.968-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-17T09:07:38.969-0300] {logging_mixin.py:137} INFO - [2023-04-17T09:07:38.969-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-17T09:07:38.969-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-17T09:07:38.974-0300] {processor.py:175} INFO - Processing /home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2023-04-17T09:08:28.768-0300] {processor.py:153} INFO - Started process (PID=82765) to work on /home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-17T09:08:28.776-0300] {processor.py:743} INFO - Processing file /home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-17T09:08:28.777-0300] {logging_mixin.py:137} INFO - [2023-04-17T09:08:28.777-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-17T09:08:28.794-0300] {logging_mixin.py:137} INFO - [2023-04-17T09:08:28.794-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-17T09:08:28.794-0300] {logging_mixin.py:137} INFO - [2023-04-17T09:08:28.794-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-17T09:08:28.795-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-17T09:08:28.799-0300] {processor.py:175} INFO - Processing /home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
