[2023-04-15T11:30:53.564-0300] {processor.py:153} INFO - Started process (PID=17737) to work on /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py
[2023-04-15T11:30:53.564-0300] {processor.py:743} INFO - Processing file /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py for tasks to queue
[2023-04-15T11:30:53.564-0300] {logging_mixin.py:137} INFO - [2023-04-15T11:30:53.564-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py
[2023-04-15T11:30:53.566-0300] {logging_mixin.py:137} INFO - [2023-04-15T11:30:53.565-0300] {dagbag.py:341} ERROR - Failed to import: /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py", line 62
    	on_success_callback: success_callback,
    	                   ^
SyntaxError: positional argument follows keyword argument
[2023-04-15T11:30:53.566-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py
[2023-04-15T11:30:53.582-0300] {processor.py:175} INFO - Processing /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py took 0.020 seconds
[2023-04-15T11:31:37.074-0300] {processor.py:153} INFO - Started process (PID=17820) to work on /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py
[2023-04-15T11:31:37.082-0300] {processor.py:743} INFO - Processing file /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py for tasks to queue
[2023-04-15T11:31:37.083-0300] {logging_mixin.py:137} INFO - [2023-04-15T11:31:37.083-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py
[2023-04-15T11:31:37.088-0300] {logging_mixin.py:137} INFO - [2023-04-15T11:31:37.087-0300] {dagbag.py:341} ERROR - Failed to import: /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py", line 62
    	on_success_callback: success_callback,
    	                   ^
SyntaxError: positional argument follows keyword argument
[2023-04-15T11:31:37.089-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py
[2023-04-15T11:31:37.127-0300] {processor.py:175} INFO - Processing /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py took 0.055 seconds
[2023-04-15T11:32:13.490-0300] {processor.py:153} INFO - Started process (PID=17905) to work on /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py
[2023-04-15T11:32:13.499-0300] {processor.py:743} INFO - Processing file /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py for tasks to queue
[2023-04-15T11:32:13.501-0300] {logging_mixin.py:137} INFO - [2023-04-15T11:32:13.501-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py
[2023-04-15T11:32:13.506-0300] {logging_mixin.py:137} INFO - [2023-04-15T11:32:13.504-0300] {dagbag.py:341} ERROR - Failed to import: /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py", line 62
    	on_success_callback: success_callback,
    	                   ^
SyntaxError: positional argument follows keyword argument
[2023-04-15T11:32:13.506-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py
[2023-04-15T11:32:13.529-0300] {processor.py:175} INFO - Processing /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py took 0.040 seconds
[2023-04-15T11:32:51.341-0300] {processor.py:153} INFO - Started process (PID=17974) to work on /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py
[2023-04-15T11:32:51.349-0300] {processor.py:743} INFO - Processing file /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py for tasks to queue
[2023-04-15T11:32:51.350-0300] {logging_mixin.py:137} INFO - [2023-04-15T11:32:51.350-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py
[2023-04-15T11:32:51.355-0300] {logging_mixin.py:137} INFO - [2023-04-15T11:32:51.354-0300] {dagbag.py:341} ERROR - Failed to import: /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py", line 62
    	on_success_callback: success_callback,
    	                   ^
SyntaxError: positional argument follows keyword argument
[2023-04-15T11:32:51.355-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py
[2023-04-15T11:32:51.371-0300] {processor.py:175} INFO - Processing /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py took 0.031 seconds
[2023-04-15T11:33:26.092-0300] {processor.py:153} INFO - Started process (PID=18038) to work on /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py
[2023-04-15T11:33:26.093-0300] {processor.py:743} INFO - Processing file /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py for tasks to queue
[2023-04-15T11:33:26.094-0300] {logging_mixin.py:137} INFO - [2023-04-15T11:33:26.094-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py
[2023-04-15T11:33:26.096-0300] {logging_mixin.py:137} INFO - [2023-04-15T11:33:26.095-0300] {dagbag.py:341} ERROR - Failed to import: /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py", line 62
    	on_success_callback: success_callback,
    	                   ^
SyntaxError: positional argument follows keyword argument
[2023-04-15T11:33:26.096-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py
[2023-04-15T11:33:26.112-0300] {processor.py:175} INFO - Processing /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py took 0.022 seconds
[2023-04-15T11:33:58.105-0300] {processor.py:153} INFO - Started process (PID=18129) to work on /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py
[2023-04-15T11:33:58.114-0300] {processor.py:743} INFO - Processing file /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py for tasks to queue
[2023-04-15T11:33:58.115-0300] {logging_mixin.py:137} INFO - [2023-04-15T11:33:58.114-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py
[2023-04-15T11:33:58.121-0300] {logging_mixin.py:137} INFO - [2023-04-15T11:33:58.118-0300] {dagbag.py:341} ERROR - Failed to import: /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py", line 62
    	on_success_callback: success_callback,
    	                   ^
SyntaxError: positional argument follows keyword argument
[2023-04-15T11:33:58.121-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py
[2023-04-15T11:33:58.146-0300] {processor.py:175} INFO - Processing /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py took 0.044 seconds
[2023-04-15T11:34:33.190-0300] {processor.py:153} INFO - Started process (PID=18193) to work on /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py
[2023-04-15T11:34:33.191-0300] {processor.py:743} INFO - Processing file /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py for tasks to queue
[2023-04-15T11:34:33.191-0300] {logging_mixin.py:137} INFO - [2023-04-15T11:34:33.191-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py
[2023-04-15T11:34:33.194-0300] {logging_mixin.py:137} INFO - [2023-04-15T11:34:33.193-0300] {dagbag.py:341} ERROR - Failed to import: /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py", line 62
    	on_success_callback: success_callback,
    	                   ^
SyntaxError: positional argument follows keyword argument
[2023-04-15T11:34:33.194-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py
[2023-04-15T11:34:33.210-0300] {processor.py:175} INFO - Processing /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py took 0.021 seconds
[2023-04-15T11:35:06.580-0300] {processor.py:153} INFO - Started process (PID=18304) to work on /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py
[2023-04-15T11:35:06.588-0300] {processor.py:743} INFO - Processing file /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py for tasks to queue
[2023-04-15T11:35:06.589-0300] {logging_mixin.py:137} INFO - [2023-04-15T11:35:06.589-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py
[2023-04-15T11:35:06.593-0300] {logging_mixin.py:137} INFO - [2023-04-15T11:35:06.593-0300] {dagbag.py:341} ERROR - Failed to import: /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py", line 62
    	on_success_callback: success_callback,
    	                   ^
SyntaxError: positional argument follows keyword argument
[2023-04-15T11:35:06.594-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py
[2023-04-15T11:35:06.610-0300] {processor.py:175} INFO - Processing /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py took 0.032 seconds
[2023-04-15T11:35:41.648-0300] {processor.py:153} INFO - Started process (PID=18376) to work on /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py
[2023-04-15T11:35:41.656-0300] {processor.py:743} INFO - Processing file /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py for tasks to queue
[2023-04-15T11:35:41.657-0300] {logging_mixin.py:137} INFO - [2023-04-15T11:35:41.657-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py
[2023-04-15T11:35:41.662-0300] {logging_mixin.py:137} INFO - [2023-04-15T11:35:41.660-0300] {dagbag.py:341} ERROR - Failed to import: /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py", line 62
    	on_success_callback: success_callback,
    	                   ^
SyntaxError: positional argument follows keyword argument
[2023-04-15T11:35:41.662-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py
[2023-04-15T11:35:41.684-0300] {processor.py:175} INFO - Processing /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py took 0.039 seconds
[2023-04-15T11:36:15.690-0300] {processor.py:153} INFO - Started process (PID=18434) to work on /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py
[2023-04-15T11:36:15.698-0300] {processor.py:743} INFO - Processing file /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py for tasks to queue
[2023-04-15T11:36:15.699-0300] {logging_mixin.py:137} INFO - [2023-04-15T11:36:15.699-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py
[2023-04-15T11:36:15.703-0300] {logging_mixin.py:137} INFO - [2023-04-15T11:36:15.702-0300] {dagbag.py:341} ERROR - Failed to import: /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py", line 62
    	on_success_callback: success_callback,
    	                   ^
SyntaxError: positional argument follows keyword argument
[2023-04-15T11:36:15.704-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py
[2023-04-15T11:36:15.736-0300] {processor.py:175} INFO - Processing /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py took 0.048 seconds
[2023-04-15T11:36:49.929-0300] {processor.py:153} INFO - Started process (PID=18501) to work on /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py
[2023-04-15T11:36:49.934-0300] {processor.py:743} INFO - Processing file /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py for tasks to queue
[2023-04-15T11:36:49.935-0300] {logging_mixin.py:137} INFO - [2023-04-15T11:36:49.935-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py
[2023-04-15T11:36:49.941-0300] {logging_mixin.py:137} INFO - [2023-04-15T11:36:49.939-0300] {dagbag.py:341} ERROR - Failed to import: /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py", line 62
    	on_success_callback: success_callback,
    	                   ^
SyntaxError: positional argument follows keyword argument
[2023-04-15T11:36:49.941-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py
[2023-04-15T11:36:49.963-0300] {processor.py:175} INFO - Processing /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py took 0.036 seconds
[2023-04-15T11:37:26.272-0300] {processor.py:153} INFO - Started process (PID=18584) to work on /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py
[2023-04-15T11:37:26.279-0300] {processor.py:743} INFO - Processing file /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py for tasks to queue
[2023-04-15T11:37:26.280-0300] {logging_mixin.py:137} INFO - [2023-04-15T11:37:26.279-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py
[2023-04-15T11:37:26.284-0300] {logging_mixin.py:137} INFO - [2023-04-15T11:37:26.283-0300] {dagbag.py:341} ERROR - Failed to import: /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py", line 62
    	on_success_callback: success_callback,
    	                   ^
SyntaxError: positional argument follows keyword argument
[2023-04-15T11:37:26.284-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py
[2023-04-15T11:37:26.305-0300] {processor.py:175} INFO - Processing /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py took 0.034 seconds
[2023-04-15T11:37:58.292-0300] {processor.py:153} INFO - Started process (PID=18656) to work on /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py
[2023-04-15T11:37:58.301-0300] {processor.py:743} INFO - Processing file /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py for tasks to queue
[2023-04-15T11:37:58.302-0300] {logging_mixin.py:137} INFO - [2023-04-15T11:37:58.301-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py
[2023-04-15T11:37:58.306-0300] {logging_mixin.py:137} INFO - [2023-04-15T11:37:58.305-0300] {dagbag.py:341} ERROR - Failed to import: /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py", line 62
    	on_success_callback: success_callback,
    	                   ^
SyntaxError: positional argument follows keyword argument
[2023-04-15T11:37:58.306-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py
[2023-04-15T11:37:58.323-0300] {processor.py:175} INFO - Processing /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py took 0.034 seconds
[2023-04-15T11:38:30.305-0300] {processor.py:153} INFO - Started process (PID=18713) to work on /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py
[2023-04-15T11:38:30.313-0300] {processor.py:743} INFO - Processing file /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py for tasks to queue
[2023-04-15T11:38:30.314-0300] {logging_mixin.py:137} INFO - [2023-04-15T11:38:30.314-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py
[2023-04-15T11:38:30.319-0300] {logging_mixin.py:137} INFO - [2023-04-15T11:38:30.318-0300] {dagbag.py:341} ERROR - Failed to import: /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py", line 62
    	on_success_callback: success_callback,
    	                   ^
SyntaxError: positional argument follows keyword argument
[2023-04-15T11:38:30.319-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py
[2023-04-15T11:38:30.342-0300] {processor.py:175} INFO - Processing /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py took 0.041 seconds
[2023-04-15T11:39:05.239-0300] {processor.py:153} INFO - Started process (PID=18829) to work on /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py
[2023-04-15T11:39:05.248-0300] {processor.py:743} INFO - Processing file /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py for tasks to queue
[2023-04-15T11:39:05.249-0300] {logging_mixin.py:137} INFO - [2023-04-15T11:39:05.249-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py
[2023-04-15T11:39:05.253-0300] {logging_mixin.py:137} INFO - [2023-04-15T11:39:05.252-0300] {dagbag.py:341} ERROR - Failed to import: /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py", line 62
    	on_success_callback: success_callback,
    	                   ^
SyntaxError: positional argument follows keyword argument
[2023-04-15T11:39:05.254-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py
[2023-04-15T11:39:05.270-0300] {processor.py:175} INFO - Processing /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py took 0.032 seconds
[2023-04-15T11:39:45.803-0300] {processor.py:153} INFO - Started process (PID=18909) to work on /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py
[2023-04-15T11:39:45.812-0300] {processor.py:743} INFO - Processing file /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py for tasks to queue
[2023-04-15T11:39:45.813-0300] {logging_mixin.py:137} INFO - [2023-04-15T11:39:45.812-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py
[2023-04-15T11:39:45.817-0300] {logging_mixin.py:137} INFO - [2023-04-15T11:39:45.816-0300] {dagbag.py:341} ERROR - Failed to import: /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py", line 62
    	on_success_callback: success_callback,
    	                   ^
SyntaxError: positional argument follows keyword argument
[2023-04-15T11:39:45.818-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py
[2023-04-15T11:39:45.841-0300] {processor.py:175} INFO - Processing /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py took 0.042 seconds
[2023-04-15T11:40:22.673-0300] {processor.py:153} INFO - Started process (PID=19011) to work on /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py
[2023-04-15T11:40:22.681-0300] {processor.py:743} INFO - Processing file /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py for tasks to queue
[2023-04-15T11:40:22.682-0300] {logging_mixin.py:137} INFO - [2023-04-15T11:40:22.682-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py
[2023-04-15T11:40:22.687-0300] {logging_mixin.py:137} INFO - [2023-04-15T11:40:22.686-0300] {dagbag.py:341} ERROR - Failed to import: /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py", line 62
    	on_success_callback: success_callback,
    	                   ^
SyntaxError: positional argument follows keyword argument
[2023-04-15T11:40:22.688-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py
[2023-04-15T11:40:22.714-0300] {processor.py:175} INFO - Processing /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py took 0.045 seconds
[2023-04-15T11:41:00.445-0300] {processor.py:153} INFO - Started process (PID=19073) to work on /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py
[2023-04-15T11:41:00.446-0300] {processor.py:743} INFO - Processing file /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py for tasks to queue
[2023-04-15T11:41:00.446-0300] {logging_mixin.py:137} INFO - [2023-04-15T11:41:00.446-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py
[2023-04-15T11:41:00.449-0300] {logging_mixin.py:137} INFO - [2023-04-15T11:41:00.448-0300] {dagbag.py:341} ERROR - Failed to import: /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py", line 62
    	on_success_callback: success_callback,
    	                   ^
SyntaxError: positional argument follows keyword argument
[2023-04-15T11:41:00.450-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py
[2023-04-15T11:41:00.470-0300] {processor.py:175} INFO - Processing /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py took 0.027 seconds
[2023-04-15T11:41:32.677-0300] {processor.py:153} INFO - Started process (PID=19136) to work on /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py
[2023-04-15T11:41:32.685-0300] {processor.py:743} INFO - Processing file /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py for tasks to queue
[2023-04-15T11:41:32.686-0300] {logging_mixin.py:137} INFO - [2023-04-15T11:41:32.686-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py
[2023-04-15T11:41:32.692-0300] {logging_mixin.py:137} INFO - [2023-04-15T11:41:32.691-0300] {dagbag.py:341} ERROR - Failed to import: /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py", line 62
    	on_success_callback: success_callback,
    	                   ^
SyntaxError: positional argument follows keyword argument
[2023-04-15T11:41:32.692-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py
[2023-04-15T11:41:32.725-0300] {processor.py:175} INFO - Processing /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py took 0.049 seconds
[2023-04-15T11:42:07.775-0300] {processor.py:153} INFO - Started process (PID=19225) to work on /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py
[2023-04-15T11:42:07.776-0300] {processor.py:743} INFO - Processing file /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py for tasks to queue
[2023-04-15T11:42:07.777-0300] {logging_mixin.py:137} INFO - [2023-04-15T11:42:07.776-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py
[2023-04-15T11:42:07.780-0300] {logging_mixin.py:137} INFO - [2023-04-15T11:42:07.779-0300] {dagbag.py:341} ERROR - Failed to import: /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py", line 63
    	on_success_callback: success_callback,
    	                   ^
SyntaxError: positional argument follows keyword argument
[2023-04-15T11:42:07.780-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py
[2023-04-15T11:42:07.807-0300] {processor.py:175} INFO - Processing /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py took 0.035 seconds
[2023-04-15T11:42:39.805-0300] {processor.py:153} INFO - Started process (PID=19371) to work on /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py
[2023-04-15T11:42:39.814-0300] {processor.py:743} INFO - Processing file /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py for tasks to queue
[2023-04-15T11:42:39.815-0300] {logging_mixin.py:137} INFO - [2023-04-15T11:42:39.814-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py
[2023-04-15T11:42:39.819-0300] {logging_mixin.py:137} INFO - [2023-04-15T11:42:39.818-0300] {dagbag.py:341} ERROR - Failed to import: /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py", line 63
    	on_success_callback: success_callback,
    	                   ^
SyntaxError: positional argument follows keyword argument
[2023-04-15T11:42:39.820-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py
[2023-04-15T11:42:39.851-0300] {processor.py:175} INFO - Processing /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py took 0.048 seconds
[2023-04-15T11:43:12.952-0300] {processor.py:153} INFO - Started process (PID=19456) to work on /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py
[2023-04-15T11:43:12.961-0300] {processor.py:743} INFO - Processing file /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py for tasks to queue
[2023-04-15T11:43:12.962-0300] {logging_mixin.py:137} INFO - [2023-04-15T11:43:12.962-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py
[2023-04-15T11:43:12.966-0300] {logging_mixin.py:137} INFO - [2023-04-15T11:43:12.965-0300] {dagbag.py:341} ERROR - Failed to import: /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py", line 63
    	on_success_callback: success_callback,
    	                   ^
SyntaxError: positional argument follows keyword argument
[2023-04-15T11:43:12.966-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py
[2023-04-15T11:43:12.983-0300] {processor.py:175} INFO - Processing /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py took 0.032 seconds
[2023-04-15T11:43:50.928-0300] {processor.py:153} INFO - Started process (PID=19598) to work on /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py
[2023-04-15T11:43:50.930-0300] {processor.py:743} INFO - Processing file /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py for tasks to queue
[2023-04-15T11:43:50.931-0300] {logging_mixin.py:137} INFO - [2023-04-15T11:43:50.931-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py
[2023-04-15T11:43:50.934-0300] {logging_mixin.py:137} INFO - [2023-04-15T11:43:50.933-0300] {dagbag.py:341} ERROR - Failed to import: /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py", line 63
    	on_success_callback: success_callback,
    	                   ^
SyntaxError: positional argument follows keyword argument
[2023-04-15T11:43:50.935-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py
[2023-04-15T11:43:50.956-0300] {processor.py:175} INFO - Processing /home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag1.py took 0.030 seconds
